project_name: logit-distillation-code-cluster
dataset: sahil2801/CodeAlpaca-20k
models:
  teacher: meta-llama/Llama-3.1-8B-Instruct
  student: meta-llama/Llama-3.2-3B-Instruct
tokenizer:
  max_length: 1024
training:
  output_dir: ./distilled_models
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8
  save_steps: 1000
  logging_steps: 1
  eval_steps: 32
  eval_strategy: steps
  save_strategy: steps
  learning_rate: 2e-5
  weight_decay: 0.05
  warmup_ratio: 0.1
  lr_scheduler_type: cosine
  resume_from_checkpoint: null # Set to a path or True to resume from the latest checkpoint
  fp16: false
  bf16: true
distillation:
  temperature: 2.0
  alpha: 0.5
  method: logit_distillation
  kl_divergence: forward
model_config:
  use_flash_attention: false
# spectrum:
#   layers_to_unfreeze: /workspace/spectrum/snr_results_Qwen-Qwen2-1.5B_unfrozenparameters_50percent.yaml # You can pass a spectrum yaml file here to freeze layers identified by spectrum.
