project_name: distil-logits
dataset:
  name: nicher92/medqa-swe
  split: train
  num_samples: 32
  seed: 42
models:
  teacher: meta-llama/Llama-3.2-3B-Instruct
  student: meta-llama/Llama-3.2-1B-Instruct
tokenizer:
  max_length: 1024
training:
  output_dir: ./results
  num_train_epochs: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1 # added plotting for validation loss
  gradient_accumulation_steps: 8
  save_steps: 1000
  logging_steps: 1
  eval_steps: 100 # added plotting for validation loss
  eval_strategy: steps # added plotting for validation loss
  save_strategy: steps # added plotting for validation loss
  learning_rate: 2e-5
  weight_decay: 0.05
  warmup_ratio: 0.1
  lr_scheduler_type: cosine
  resume_from_checkpoint: null  # Set to a path or True to resume from the latest checkpoint
  fp16: false
  bf16: true
  remove_unused_columns: false  # TODO: My addition, important to keep teacher input columns
distillation:
  temperature: 2.0
  alpha: 0.5
  method: soft_targets
model_config:
  use_flash_attention: false
# spectrum:
#   layers_to_unfreeze: /workspace/spectrum/snr_results_Qwen-Qwen2-1.5B_unfrozenparameters_50percent.yaml # You can pass a spectrum yaml file here to freeze layers identified by spectrum.
