project_name: logit-distillation-pubmedqa-random-sampled-teacher-output
dataset: qiaojin/PubMedQA
output_generation:
  max_new_tokens: 512
  model: meta-llama/Llama-3.1-8B-Instruct # TODO: change back to 70B
  draws: 1_000_000
  tau: 0.8
  batch_size: 8
  start_idx: 16 # TODO: change back to 0
  logits_dir: generated_tokens/pubmedqa/
distillation:
  student: meta-llama/Llama-3.1-8B-Instruct
  max_length: 1024
  use_flash_attention: false
  temperature: 2.0
  kl_divergence: forward
training:
  output_dir: ./distilled_models/random_sampling_sparse_logits
  num_train_epochs: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  save_steps: 1000
  logging_steps: 1
  eval_steps: 28
  eval_strategy: steps
  save_strategy: steps
  learning_rate: 2e-5
  weight_decay: 0.05
  warmup_ratio: 0.1
  lr_scheduler_type: cosine
  resume_from_checkpoint: null # Set to a path or True to resume from the latest checkpoint
  fp16: false
  bf16: true

