project_name: logit-dist-rand-sampled-teacher-generated-logits
dataset:
  # name: tatsu-lab/alpaca
  name: roskoN/dailydialog
  split: train
  num_samples: 320
  seed: 42
  teacher_data:
    max_new_tokens: 512
    # logits_path: generated_tokens/sassy/teacher_random_logits_320_R10000.pt
    logits_path: generated_tokens/dailydialog/teacher_random_logits_320_R10000.pt
    # system_prompt: <|begin_of_text|><|start_header_id|>system<|end_header_id|>You're a sassy teenager. Answer the following question in a sassy way.<|eot_id|><|start_header_id|>user<|end_header_id|>
    system_prompt: <|begin_of_text|><|start_header_id|>system<|end_header_id|>Översätt den här vardagliga konversationen från engelska till naturlig svenska. Använd uttryck och formuleringar som en person med svenska som modersmål faktiskt skulle säga i samma situation. Fånga tonen och känslan i samtalet – inte bara orden. Svara enbart med översättningen.<|eot_id|><|start_header_id|>user<|end_header_id|>
models:
  teacher: meta-llama/Llama-3.2-3B-Instruct
  student: meta-llama/Llama-3.2-1B-Instruct
tokenizer:
  max_length: 1024
training:
  output_dir: ./results
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8
  save_steps: 1000
  logging_steps: 1
  eval_steps: 30000 # added plotting for validation loss #TODO: change to something reasonable
  eval_strategy: steps
  save_strategy: steps
  learning_rate: 2e-5
  weight_decay: 0.05
  warmup_ratio: 0.1
  lr_scheduler_type: cosine
  resume_from_checkpoint: null # Set to a path or True to resume from the latest checkpoint
  fp16: false
  bf16: true
distillation:
  temperature: 2.0
  alpha: 0.5
  method: distillation_on_random_sampled_teacher_generated_logits
model_config:
  use_flash_attention: false
# spectrum:
#   layers_to_unfreeze: /workspace/spectrum/snr_results_Qwen-Qwen2-1.5B_unfrozenparameters_50percent.yaml # You can pass a spectrum yaml file here to freeze layers identified by spectrum.
