project_name: logit-distillation-pubmedqa-random-sampled-teacher-output
dataset: qiaojin/PubMedQA
output_generation:
  max_new_tokens: 512
  model: meta-llama/Llama-3.3-70B-Instruct
  draws: 1_000_000
  tau: 0.7
  batch_size: 8
  logits_dir: generated_tokens/pubmedqa/
