project_name: logit-distillation-medqa-swe-random-sampled-teacher-output
dataset: 
  name: kaans/medqa-swe-with-responses
  num_samples: 3000
output_generation:
  max_new_tokens: 512
  model: meta-llama/Llama-3.3-70B-Instruct 
  draws: 10_000
  tau: 0.8
  batch_size: 16
  start_idx: 0
  logits_dir: generated_tokens/medqa_swe/
distillation:
  student: meta-llama/Llama-3.1-8B-Instruct
  logits_path: /leonardo_work/EUHPC_D17_084/DistillKit/generated_tokens/medqa_swe/combined_sparse_logits_3000.pt
  max_length: 1024
  use_flash_attention: false 
  temperature: 1.0
  kl_divergence: forward # currently reverse isn't supported 
training:
  output_dir: ./distilled_models/random_sampling_sparse_logits
  num_train_epochs: 3
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 8
  logging_steps: 1
  eval_strategy: epoch
  save_strategy: epoch
  learning_rate: 2e-5
  weight_decay: 0.05
  warmup_ratio: 0.1
  lr_scheduler_type: cosine
  resume_from_checkpoint: null # Set to a path or True to resume from the latest checkpoint
  fp16: false
  bf16: true
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  greater_is_better: false
  early_stopping_patience: 1

